[package]
name = "rust_web_scraper"   # <- tem que bater com o nome usado no COPY
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
scraper = "0.13"
warp = "0.3"
tokio = { version = "1", features = ["full"] }
